var aipinsfoto = function (campos_requeridos) {
    var self = this;
    self.idaipinsfoto = ko.observable(0);
    self.idaipinsenc = ko.observable(0);
    self.comboinsenc = ko.observableArray();
    self.nsecinsfoto = ko.observable(0);
    self.xrutainsfoto = ko.observable("");
    self.xurlinsfoto = ko.observable("");
    self.xtituinsfoto = ko.observable("");
    self.xnomarchinsfoto = ko.observable("");
    self.xextinsfoto = ko.observable("");
    self.xlatcinsfoto = ko.observable("");
    self.xlonginsfoto = ko.observable("");
    self.ioriginsfoto = ko.observable("");
    self.xdescinsfoto = ko.observable("");
    self.iestatinsfoto = ko.observable("");
    self.comboestatinsfoto = ko.observableArray();
    self.fcreaaipinsfoto = ko.observable();
    self.idseglogreg = ko.observable(0);
}
