var aipinsenc = function (campos_requeridos) {
    var self = this;
    self.idaipinsenc = ko.observable(0);
    self.idaipactivperi = ko.observable(0);
    self.idaipinsintext = ko.observable(0);
    self.itipoinsenc = ko.observable("");
    self.idaipinsmotiv = ko.observable(0);
    self.combotipoinsenc = ko.observableArray();
    self.idsegmanusu = ko.observable(0);
    self.combomanusu = ko.observableArray();
    self.xcedpropinsenc = ko.observable("");
    self.xcedsidoinsenc = ko.observable("");
    self.xplacinsenc = ko.observable("");
    self.xsermotinsenc = ko.observable("");
    self.xsercarrinsenc = ko.observable("");
    self.xnumpolinsenc = ko.observable("");
    self.xnumsininsenc = ko.observable("");    
    self.xllavinsenc = ko.observable("");
    self.xnomprodinsenc = ko.observable("");
    self.xnomprodtorinsenc = ko.observable("");
    self.xnomramopolizinsenc = ko.observable("");
    self.xnomsucinsinsenc = ko.observable("");
    self.xnuminspinsenc = ko.observable(""); //numero de inspeccion
    self.fcreainsenc = ko.observable("");
    self.fprocinsenc = ko.observable("");
    self.faudinsenc = ko.observable("");
    self.fultrechinsenc = ko.observable("");
    self.fcancinsenc = ko.observable("");
    self.facepinsenc = ko.observable("");
    self.xdescinsenc = ko.observable("");
    self.iestatinsenc = ko.observable("");
    self.comboestatinsenc = ko.observableArray();
    self.idseglogreg = ko.observable(0);
}
