var aipinsajussinmobr = function (campos_requeridos) {
    var self = this;
    self.idaipinsajussinmobr = ko.observable(0);
    self.idaipinsajussin = ko.observable(0);
    self.comboinsajussin = ko.observableArray();
    self.idaipbaremobr = ko.observable(0);
    self.combobaremobr = ko.observableArray();
    self.idaipsusrepu = ko.observable(0);
    self.combosusrepu = ko.observableArray();
    self.idaipsustam = ko.observable(0);
    self.combosustam = ko.observableArray();
    self.idaipsusmat = ko.observable(0);
    self.combosusmat = ko.observableArray();
    self.idaipsusmobr = ko.observable(0);
    self.combosusmobr = ko.observableArray();
    self.ncantinsajussinmobr = ko.observable(0);
    self.nprecfininsajussinmobr = ko.observable(0);
    self.xdescinsajussinmobr = ko.observable("");
    self.iestatinsajussinmobr = ko.observable("");
    self.comboestatinsajussinmobr = ko.observableArray();
    self.idseglogreg = ko.observable(0);
}
