var persaipinssini = function (campos_requeridos) {
    var self = this;
    self.idsegmanorg = ko.observable(0);
    self.idsegmanusuperit = ko.observable(0);
    self.idcomunmanestado = ko.observable(0);
    self.idcomunmanlocalid = ko.observable(0);
    self.itipoinsinssini = ko.observable("");
    self.xnacioninssini = ko.observable("");
    self.xcedpropinssini = ko.observable("");
    self.finicioinssini = ko.observable("");
    self.itipoinssini = ko.observable("");
    self.xplacainssini = ko.observable("");
    self.ffininssini = ko.observable("");
    self.icausainssini = ko.observable("");
    self.focurrinssini = ko.observable("");
    self.fdeclarinssini = ko.observable("");
    self.fnotifinssini = ko.observable("");
    self.xnuminssini = ko.observable("");
    self.xdireccioninssini = ko.observable("");
    self.xdescinssini = ko.observable("");
}
