self.limpiar = function () {
    self.idaipinslimsus(0);
    self.itipoinsenc("");
    self.idsegmanusu(0);
    self.xcedula("");
    self.xnombres("");
    self.xapellidos("");
    self.xnombrecompleto("");
    self.xcedpropinsenc("");
    self.xcedsidoinsenc("");
    self.xplacinsenc("");
    self.xsermotinsenc("");
    self.nfactinslimsus(0);
    self.irepuinslimsus(0);
    self.imobrinslimsus(0);
    self.xnomaseginslimsus("");
    self.idaipmanveh(0);
    self.xsucuinslimsus("");
    self.nkiloinslimsus(0);
    self.xdescinslimsus("");
    self.iestatinslimsus("");
    self.idseglogreg(0);
}
