var vi_aipinslimsusrepu = function (campos_requeridos) {
    var self = this;
    self.idaipinslimsusrepu = ko.observable(0);
    self.comboinslimsusrepu = ko.observableArray();
    self.idaipinslimsus = ko.observable(0);
    self.comboinslimsus = ko.observableArray();
    self.idaipinsenc = ko.observable(0);
    self.comboinsenc = ko.observableArray();
    self.itipoinsenc = ko.observable("");
    self.combotipoinsenc = ko.observableArray();
    self.idaipbarerepu = ko.observable(0);
    self.combobarerepu = ko.observableArray();
    self.idaipmanrepu = ko.observable(0);
    self.combomanrepu = ko.observableArray();
    self.xnommanrepu = ko.observable("");
    self.faplibarerepu = ko.observable("");
    self.iorigbarerepu = ko.observable("");
    self.comboorigbarerepu = ko.observableArray();
    self.mcostbarerepu = ko.observable(0);
    self.ncantinslimsusrepu = ko.observable(0);
    self.nprecfininslimsusrepu = ko.observable(0);
    self.xdescinslimsusrepu = ko.observable("");
    self.iestatinslimsusrepu = ko.observable("");
    self.comboestatinslimsusrepu = ko.observableArray();
    self.idseglogreg = ko.observable(0);
}
