self.limpiar = function () {
    self.idaipinssinmobr(0);
    self.idaipinssin(0);
    self.idaipinsenc(0);
    self.itipoinsenc("");
    self.idaipbaremobr(0);
    self.idaipmanrepu(0);
    self.xnommanrepu("");
    self.faplibaremobr("");
    self.itipobaremobr("");
    self.itamapiezbaremobr("");
    self.imaterpiezbaremobr("");
    self.mcostbaremobr(0);
    self.xdescbaremobr("");
    self.ncantinssinmobr(0);
    self.nprecfininssinmobr(0);
    self.xdescinssinmobr("");
    self.iestatinssinmobr("");
    self.idseglogreg(0);
}
