self.limpiar = function () {
    self.idaipinsajusanexmobr(0);
    self.idaipinsajusanex(0);
    self.idaipinsenc(0);
    self.itipoinsenc("");
    self.idaipbaremobr(0);
    self.idaipmanrepu(0);
    self.xnommanrepu("");
    self.faplibaremobr("");
    self.itipobaremobr("");
    self.itamapiezbaremobr("");
    self.imaterpiezbaremobr("");
    self.mcostbaremobr(0);
    self.xdescbaremobr("");
    self.ncantinsajusanexmobr(0);
    self.nprecfininsajusanexmobr(0);
    self.xdescinsajusanexmobr("");
    self.iestatinsajusanexmobr("");
    self.idseglogreg(0);
}
