var vi_aipinsajusanexrepu = function (campos_requeridos) {
    var self = this;
    self.idaipinsajusanexrepu = ko.observable(0);
    self.comboinsajusanexrepu = ko.observableArray();
    self.idaipinsajusanex = ko.observable(0);
    self.comboinsajusanex = ko.observableArray();
    self.idaipinsenc = ko.observable(0);
    self.comboinsenc = ko.observableArray();
    self.itipoinsenc = ko.observable("");
    self.combotipoinsenc = ko.observableArray();
    self.idaipbarerepu = ko.observable(0);
    self.combobarerepu = ko.observableArray();
    self.idaipmanrepu = ko.observable(0);
    self.combomanrepu = ko.observableArray();
    self.xnommanrepu = ko.observable("");
    self.faplibarerepu = ko.observable("");
    self.iorigbarerepu = ko.observable("");
    self.comboorigbarerepu = ko.observableArray();
    self.mcostbarerepu = ko.observable(0);
}
