self.limpiar = function () {
    self.idaipmanveh(0);
    self.idaipmanvehmar(0);
    self.idaipmanvehmod(0);
    self.idaipmanvehver(0);
    self.itipotransmanveh("");
    self.itipomanveh("");
    self.iclasemanveh("");
    self.icolormanveh("");
    self.xplacamanveh("");
    self.xsercarrmanveh("");
    self.xsermotmanveh("");
    self.itraccmanveh("");
    self.iimpmanveh(0);
    self.ncilinmanveh(0);
    self.xcargmanveh("");
    self.xcapmanveh("");
    self.xdescmanveh("");
    self.iestatmanveh("");
    self.idseglogreg(0);
}
