var vi_segusudetperf = function (campos_requeridos) {
    var self = this;
    self.idsegusuperf = ko.observable(0);
    self.combousuperf = ko.observableArray();
    self.idsegmanusu = ko.observable(0);
    self.combomanusu = ko.observableArray();
    self.idsegappperf = ko.observable(0);
    self.comboappperf = ko.observableArray();
    self.idcomunmanpers = ko.observable(0);
    self.combounmanpers = ko.observableArray();
    self.idsegmandep = ko.observable(0);
    self.combomandep = ko.observableArray();
    self.idsegmancarg = ko.observable(0);
    self.combomancarg = ko.observableArray();
    self.xnombreusuario = ko.observable("");
    self.idsegmanapp = ko.observable(0);
    self.combomanapp = ko.observableArray();
    self.idsegmanperf = ko.observable(0);
    self.combomanperf = ko.observableArray();
    self.xnombredep = ko.observable("");
    self.xnombrecarg = ko.observable("");
    self.xnombreperf = ko.observable("");
    self.nnivelperf = ko.observable(0);
    self.xcedula = ko.observable("");
    self.xnombrecompleto = ko.observable("");
    self.xabrevperf = ko.observable("");
    self.xnombrecorto = ko.observable("");
    self.xnombrelargo = ko.observable("");
}
